name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.6.7
  dio: ^5.4.0
  logger: ^2.0.2
  flutter_bloc: ^8.1.4
  path_provider: ^2.1.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  openvpn_flutter: ^1.2.2
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  # assets:
  #   - resources/langs/

