name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  flutter_svg: ^2.0.9
  # easy_localization: ^3.0.7
  server_list_screen:
    path: ../feature/server_list_screen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
